spring.config.import=file:src/main/resources/application.properties

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/db/migration/schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
