spring.application.name=bookstore
spring.config.import=file:src/main/resources/application-private.properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver
