spring.application.name=bookstore
spring.config.import=file:src/main/resources/application-private.properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver
#server.servlet.context-path=/api
s3.endpoint=http://localhost:8333
s3.region=us-east-1
s3.bucket-name=bookstore-bucket
