spring.application.name=bookstore
spring.config.import=file:src/main/resources/application-private.properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver
#server.servlet.context-path=/api
s3.endpoint=http://localhost:8333
s3.region=us-east-1
s3.bucket-name=bookstore-bucket

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=synchronous-kafka-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=me.crvena.bookstore.*
spring.kafka.properties.allow.auto.create.topics=true

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.timeout=1000
spring.cache.type=redis

service.external.cover-api.internal-url=http://localhost:8000/img/
service.external.cover-api.external-url=http://localhost:8000/img/
