
    create table book (
        available boolean default true not null,
        price numeric(19,2) default 0 not null check (price>=0),
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        id bigint generated by default as identity,
        sales bigint default 0 not null,
        stock bigint default 0 not null,
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        version bigint default 0,
        author varchar(50) not null,
        cover varchar(255),
        description TEXT default '',
        title varchar(255) not null,
        primary key (id),
        unique (title, author)
    );

    create table book_tags (
        book_id bigint not null,
        tag_id bigint not null,
        primary key (book_id, tag_id)
    );

    create table cart_item (
        book_id bigint not null,
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        creator_id bigint not null,
        id bigint generated by default as identity,
        number bigint default 1 not null check (number>=1),
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        version bigint default 0,
        primary key (id),
        constraint unique_cart_item_book_creator unique (book_id, creator_id)
    );

    create table order_item (
        paid_price numeric(19,2) not null check (paid_price>=0),
        unit_price numeric(19,2) not null check (unit_price>=0),
        book_id bigint not null,
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        id bigint generated by default as identity,
        number bigint default 1 not null check (number>=1),
        order_id bigint not null,
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        version bigint default 0,
        primary key (id)
    );

    create table orders (
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        creator_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        version bigint default 0,
        tel varchar(30),
        receiver varchar(50),
        address varchar(100),
        primary key (id)
    );

    create table tag (
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        version bigint default 0,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table user_info (
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        user_id bigint not null,
        version bigint default 0,
        avatar varchar(255),
        introduction varchar(255),
        nickname varchar(255),
        primary key (user_id)
    );

    create table users (
        account_non_expired boolean default true not null,
        account_non_locked boolean default true not null,
        balance numeric(19,2) default 0 not null,
        enabled boolean default true not null,
        created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
        version bigint default 0,
        username varchar(50) not null unique,
        email varchar(255) not null unique,
        password varchar(255) not null,
        role varchar(255) default 'USER' not null check (role in ('USER','ADMIN')),
        primary key (id)
    );

    create index IDXg0286ag1dlt4473st1ugemd0m 
       on book (title);

    create index IDXrai096pq6coakhlef212hpi3d 
       on book (author);

    create index IDX1wdpsed5kna2y38hnbgrnhi5b 
       on tag (name);

    create index IDXr43af9ap4edm43mmtq01oddj6 
       on users (username);

    alter table if exists book_tags 
       add constraint FKbgb421y3jrqvhqjo5ktpthb1d 
       foreign key (tag_id) 
       references tag;

    alter table if exists book_tags 
       add constraint FKgrb34gudrjkbeew59bty9sh45 
       foreign key (book_id) 
       references book;

    alter table if exists cart_item 
       add constraint FKis5hg85qbs5d91etr4mvd4tx6 
       foreign key (book_id) 
       references book 
       on delete cascade;

    alter table if exists cart_item 
       add constraint FKcbfekcwoew33w6yotcs9x05lj 
       foreign key (creator_id) 
       references users 
       on delete cascade;

    alter table if exists order_item 
       add constraint FKb033an1f8qmpbnfl0a6jb5njs 
       foreign key (book_id) 
       references book 
       on delete restrict;

    alter table if exists order_item 
       add constraint FKt4dc2r9nbvbujrljv3e23iibt 
       foreign key (order_id) 
       references orders 
       on delete cascade;

    alter table if exists orders 
       add constraint FKtjvw78tj731d1puuoaps78oay 
       foreign key (creator_id) 
       references users 
       on delete restrict;

    alter table if exists user_info 
       add constraint FKr1b96ca4asuvrhwoqkdmbo7nj 
       foreign key (user_id) 
       references users 
       on delete cascade;
