/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as OrderImport } from './routes/order'
import { Route as MeImport } from './routes/me'
import { Route as LoginImport } from './routes/login'
import { Route as CartImport } from './routes/cart'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as MeIndexImport } from './routes/me/index'
import { Route as BookIndexImport } from './routes/book/index'
import { Route as MeStatsImport } from './routes/me/stats'
import { Route as MeStarsImport } from './routes/me/stars'
import { Route as MeRebalanceImport } from './routes/me/rebalance'
import { Route as MeProfileImport } from './routes/me/profile'
import { Route as MePasswordImport } from './routes/me/password'
import { Route as MeCommentsImport } from './routes/me/comments'
import { Route as MeAddressImport } from './routes/me/address'
import { Route as BookBookIdImport } from './routes/book/$bookId'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminBooksImport } from './routes/admin/books'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const OrderRoute = OrderImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MeIndexRoute = MeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)

const BookIndexRoute = BookIndexImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRoute,
} as any)

const MeStatsRoute = MeStatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => MeRoute,
} as any)

const MeStarsRoute = MeStarsImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => MeRoute,
} as any)

const MeRebalanceRoute = MeRebalanceImport.update({
  id: '/rebalance',
  path: '/rebalance',
  getParentRoute: () => MeRoute,
} as any)

const MeProfileRoute = MeProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeRoute,
} as any)

const MePasswordRoute = MePasswordImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => MeRoute,
} as any)

const MeCommentsRoute = MeCommentsImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => MeRoute,
} as any)

const MeAddressRoute = MeAddressImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => MeRoute,
} as any)

const BookBookIdRoute = BookBookIdImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBooksRoute = AdminBooksImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksImport
      parentRoute: typeof AdminImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdImport
      parentRoute: typeof rootRoute
    }
    '/me/address': {
      id: '/me/address'
      path: '/address'
      fullPath: '/me/address'
      preLoaderRoute: typeof MeAddressImport
      parentRoute: typeof MeImport
    }
    '/me/comments': {
      id: '/me/comments'
      path: '/comments'
      fullPath: '/me/comments'
      preLoaderRoute: typeof MeCommentsImport
      parentRoute: typeof MeImport
    }
    '/me/password': {
      id: '/me/password'
      path: '/password'
      fullPath: '/me/password'
      preLoaderRoute: typeof MePasswordImport
      parentRoute: typeof MeImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileImport
      parentRoute: typeof MeImport
    }
    '/me/rebalance': {
      id: '/me/rebalance'
      path: '/rebalance'
      fullPath: '/me/rebalance'
      preLoaderRoute: typeof MeRebalanceImport
      parentRoute: typeof MeImport
    }
    '/me/stars': {
      id: '/me/stars'
      path: '/stars'
      fullPath: '/me/stars'
      preLoaderRoute: typeof MeStarsImport
      parentRoute: typeof MeImport
    }
    '/me/stats': {
      id: '/me/stats'
      path: '/stats'
      fullPath: '/me/stats'
      preLoaderRoute: typeof MeStatsImport
      parentRoute: typeof MeImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookIndexImport
      parentRoute: typeof rootRoute
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexImport
      parentRoute: typeof MeImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MeRouteChildren {
  MeAddressRoute: typeof MeAddressRoute
  MeCommentsRoute: typeof MeCommentsRoute
  MePasswordRoute: typeof MePasswordRoute
  MeProfileRoute: typeof MeProfileRoute
  MeRebalanceRoute: typeof MeRebalanceRoute
  MeStarsRoute: typeof MeStarsRoute
  MeStatsRoute: typeof MeStatsRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAddressRoute: MeAddressRoute,
  MeCommentsRoute: MeCommentsRoute,
  MePasswordRoute: MePasswordRoute,
  MeProfileRoute: MeProfileRoute,
  MeRebalanceRoute: MeRebalanceRoute,
  MeStarsRoute: MeStarsRoute,
  MeStatsRoute: MeStatsRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/order': typeof OrderRoute
  '/signup': typeof SignupRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/me/address': typeof MeAddressRoute
  '/me/comments': typeof MeCommentsRoute
  '/me/password': typeof MePasswordRoute
  '/me/profile': typeof MeProfileRoute
  '/me/rebalance': typeof MeRebalanceRoute
  '/me/stars': typeof MeStarsRoute
  '/me/stats': typeof MeStatsRoute
  '/book': typeof BookIndexRoute
  '/me/': typeof MeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/signup': typeof SignupRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/me/address': typeof MeAddressRoute
  '/me/comments': typeof MeCommentsRoute
  '/me/password': typeof MePasswordRoute
  '/me/profile': typeof MeProfileRoute
  '/me/rebalance': typeof MeRebalanceRoute
  '/me/stars': typeof MeStarsRoute
  '/me/stats': typeof MeStatsRoute
  '/book': typeof BookIndexRoute
  '/me': typeof MeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/order': typeof OrderRoute
  '/signup': typeof SignupRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/me/address': typeof MeAddressRoute
  '/me/comments': typeof MeCommentsRoute
  '/me/password': typeof MePasswordRoute
  '/me/profile': typeof MeProfileRoute
  '/me/rebalance': typeof MeRebalanceRoute
  '/me/stars': typeof MeStarsRoute
  '/me/stats': typeof MeStatsRoute
  '/book/': typeof BookIndexRoute
  '/me/': typeof MeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/login'
    | '/me'
    | '/order'
    | '/signup'
    | '/admin/books'
    | '/admin/users'
    | '/book/$bookId'
    | '/me/address'
    | '/me/comments'
    | '/me/password'
    | '/me/profile'
    | '/me/rebalance'
    | '/me/stars'
    | '/me/stats'
    | '/book'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/login'
    | '/order'
    | '/signup'
    | '/admin/books'
    | '/admin/users'
    | '/book/$bookId'
    | '/me/address'
    | '/me/comments'
    | '/me/password'
    | '/me/profile'
    | '/me/rebalance'
    | '/me/stars'
    | '/me/stats'
    | '/book'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/login'
    | '/me'
    | '/order'
    | '/signup'
    | '/admin/books'
    | '/admin/users'
    | '/book/$bookId'
    | '/me/address'
    | '/me/comments'
    | '/me/password'
    | '/me/profile'
    | '/me/rebalance'
    | '/me/stars'
    | '/me/stats'
    | '/book/'
    | '/me/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  OrderRoute: typeof OrderRoute
  SignupRoute: typeof SignupRoute
  BookBookIdRoute: typeof BookBookIdRoute
  BookIndexRoute: typeof BookIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  OrderRoute: OrderRoute,
  SignupRoute: SignupRoute,
  BookBookIdRoute: BookBookIdRoute,
  BookIndexRoute: BookIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/cart",
        "/login",
        "/me",
        "/order",
        "/signup",
        "/book/$bookId",
        "/book/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/books",
        "/admin/users"
      ]
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/me": {
      "filePath": "me.tsx",
      "children": [
        "/me/address",
        "/me/comments",
        "/me/password",
        "/me/profile",
        "/me/rebalance",
        "/me/stars",
        "/me/stats",
        "/me/"
      ]
    },
    "/order": {
      "filePath": "order.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/admin/books": {
      "filePath": "admin/books.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/book/$bookId": {
      "filePath": "book/$bookId.tsx"
    },
    "/me/address": {
      "filePath": "me/address.tsx",
      "parent": "/me"
    },
    "/me/comments": {
      "filePath": "me/comments.tsx",
      "parent": "/me"
    },
    "/me/password": {
      "filePath": "me/password.tsx",
      "parent": "/me"
    },
    "/me/profile": {
      "filePath": "me/profile.tsx",
      "parent": "/me"
    },
    "/me/rebalance": {
      "filePath": "me/rebalance.tsx",
      "parent": "/me"
    },
    "/me/stars": {
      "filePath": "me/stars.tsx",
      "parent": "/me"
    },
    "/me/stats": {
      "filePath": "me/stats.tsx",
      "parent": "/me"
    },
    "/book/": {
      "filePath": "book/index.tsx"
    },
    "/me/": {
      "filePath": "me/index.tsx",
      "parent": "/me"
    }
  }
}
ROUTE_MANIFEST_END */
