/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TableImport } from './routes/table'
import { Route as OrderImport } from './routes/order'
import { Route as MeImport } from './routes/me'
import { Route as CartImport } from './routes/cart'
import { Route as MeIndexImport } from './routes/me/index'
import { Route as BookIndexImport } from './routes/book/index'
import { Route as MeStarsImport } from './routes/me/stars'
import { Route as MeProfileImport } from './routes/me/profile'
import { Route as MePasswordImport } from './routes/me/password'
import { Route as MeCommentsImport } from './routes/me/comments'
import { Route as MeAddressImport } from './routes/me/address'
import { Route as BookBookIdImport } from './routes/book/$bookId'

// Create Virtual Routes

const QueryLazyImport = createFileRoute('/query')()
const FormLazyImport = createFileRoute('/form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const QueryLazyRoute = QueryLazyImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/query.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const TableRoute = TableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRoute,
} as any)

const OrderRoute = OrderImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MeIndexRoute = MeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)

const BookIndexRoute = BookIndexImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRoute,
} as any)

const MeStarsRoute = MeStarsImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => MeRoute,
} as any)

const MeProfileRoute = MeProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeRoute,
} as any)

const MePasswordRoute = MePasswordImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => MeRoute,
} as any)

const MeCommentsRoute = MeCommentsImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => MeRoute,
} as any)

const MeAddressRoute = MeAddressImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => MeRoute,
} as any)

const BookBookIdRoute = BookBookIdImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryLazyImport
      parentRoute: typeof rootRoute
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdImport
      parentRoute: typeof rootRoute
    }
    '/me/address': {
      id: '/me/address'
      path: '/address'
      fullPath: '/me/address'
      preLoaderRoute: typeof MeAddressImport
      parentRoute: typeof MeImport
    }
    '/me/comments': {
      id: '/me/comments'
      path: '/comments'
      fullPath: '/me/comments'
      preLoaderRoute: typeof MeCommentsImport
      parentRoute: typeof MeImport
    }
    '/me/password': {
      id: '/me/password'
      path: '/password'
      fullPath: '/me/password'
      preLoaderRoute: typeof MePasswordImport
      parentRoute: typeof MeImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileImport
      parentRoute: typeof MeImport
    }
    '/me/stars': {
      id: '/me/stars'
      path: '/stars'
      fullPath: '/me/stars'
      preLoaderRoute: typeof MeStarsImport
      parentRoute: typeof MeImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookIndexImport
      parentRoute: typeof rootRoute
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexImport
      parentRoute: typeof MeImport
    }
  }
}

// Create and export the route tree

interface MeRouteChildren {
  MeAddressRoute: typeof MeAddressRoute
  MeCommentsRoute: typeof MeCommentsRoute
  MePasswordRoute: typeof MePasswordRoute
  MeProfileRoute: typeof MeProfileRoute
  MeStarsRoute: typeof MeStarsRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAddressRoute: MeAddressRoute,
  MeCommentsRoute: MeCommentsRoute,
  MePasswordRoute: MePasswordRoute,
  MeProfileRoute: MeProfileRoute,
  MeStarsRoute: MeStarsRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cart': typeof CartRoute
  '/me': typeof MeRouteWithChildren
  '/order': typeof OrderRoute
  '/table': typeof TableRoute
  '/form': typeof FormLazyRoute
  '/query': typeof QueryLazyRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/me/address': typeof MeAddressRoute
  '/me/comments': typeof MeCommentsRoute
  '/me/password': typeof MePasswordRoute
  '/me/profile': typeof MeProfileRoute
  '/me/stars': typeof MeStarsRoute
  '/book': typeof BookIndexRoute
  '/me/': typeof MeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cart': typeof CartRoute
  '/order': typeof OrderRoute
  '/table': typeof TableRoute
  '/form': typeof FormLazyRoute
  '/query': typeof QueryLazyRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/me/address': typeof MeAddressRoute
  '/me/comments': typeof MeCommentsRoute
  '/me/password': typeof MePasswordRoute
  '/me/profile': typeof MeProfileRoute
  '/me/stars': typeof MeStarsRoute
  '/book': typeof BookIndexRoute
  '/me': typeof MeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cart': typeof CartRoute
  '/me': typeof MeRouteWithChildren
  '/order': typeof OrderRoute
  '/table': typeof TableRoute
  '/form': typeof FormLazyRoute
  '/query': typeof QueryLazyRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/me/address': typeof MeAddressRoute
  '/me/comments': typeof MeCommentsRoute
  '/me/password': typeof MePasswordRoute
  '/me/profile': typeof MeProfileRoute
  '/me/stars': typeof MeStarsRoute
  '/book/': typeof BookIndexRoute
  '/me/': typeof MeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/me'
    | '/order'
    | '/table'
    | '/form'
    | '/query'
    | '/book/$bookId'
    | '/me/address'
    | '/me/comments'
    | '/me/password'
    | '/me/profile'
    | '/me/stars'
    | '/book'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/order'
    | '/table'
    | '/form'
    | '/query'
    | '/book/$bookId'
    | '/me/address'
    | '/me/comments'
    | '/me/password'
    | '/me/profile'
    | '/me/stars'
    | '/book'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/me'
    | '/order'
    | '/table'
    | '/form'
    | '/query'
    | '/book/$bookId'
    | '/me/address'
    | '/me/comments'
    | '/me/password'
    | '/me/profile'
    | '/me/stars'
    | '/book/'
    | '/me/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CartRoute: typeof CartRoute
  MeRoute: typeof MeRouteWithChildren
  OrderRoute: typeof OrderRoute
  TableRoute: typeof TableRoute
  FormLazyRoute: typeof FormLazyRoute
  QueryLazyRoute: typeof QueryLazyRoute
  BookBookIdRoute: typeof BookBookIdRoute
  BookIndexRoute: typeof BookIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CartRoute: CartRoute,
  MeRoute: MeRouteWithChildren,
  OrderRoute: OrderRoute,
  TableRoute: TableRoute,
  FormLazyRoute: FormLazyRoute,
  QueryLazyRoute: QueryLazyRoute,
  BookBookIdRoute: BookBookIdRoute,
  BookIndexRoute: BookIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cart",
        "/me",
        "/order",
        "/table",
        "/form",
        "/query",
        "/book/$bookId",
        "/book/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/me": {
      "filePath": "me.tsx",
      "children": [
        "/me/address",
        "/me/comments",
        "/me/password",
        "/me/profile",
        "/me/stars",
        "/me/"
      ]
    },
    "/order": {
      "filePath": "order.tsx"
    },
    "/table": {
      "filePath": "table.tsx"
    },
    "/form": {
      "filePath": "form.lazy.tsx"
    },
    "/query": {
      "filePath": "query.lazy.tsx"
    },
    "/book/$bookId": {
      "filePath": "book/$bookId.tsx"
    },
    "/me/address": {
      "filePath": "me/address.tsx",
      "parent": "/me"
    },
    "/me/comments": {
      "filePath": "me/comments.tsx",
      "parent": "/me"
    },
    "/me/password": {
      "filePath": "me/password.tsx",
      "parent": "/me"
    },
    "/me/profile": {
      "filePath": "me/profile.tsx",
      "parent": "/me"
    },
    "/me/stars": {
      "filePath": "me/stars.tsx",
      "parent": "/me"
    },
    "/book/": {
      "filePath": "book/index.tsx"
    },
    "/me/": {
      "filePath": "me/index.tsx",
      "parent": "/me"
    }
  }
}
ROUTE_MANIFEST_END */
